In [1]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)


[[1 2]
 [3 4]]


In [2]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [3]:
a = np.array([1, 2, 3], dtype = bool) 
print(a)

[ True  True  True]


In [4]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [5]:
print(np.dtype(a[0]))

complex128


In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [7]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [9]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)


[[1 1]
 [1 1]]
