In [48]:
import numpy as np
com = np.dtype([('inj','f4')])
a = np.array([1,2,4], dtype=com)
print(a)
print(a.dtype)

[(1.,) (2.,) (4.,)]
[('inj', '<f4')]


In [37]:
b = np.arange(24)
print(b)
b.shape=(6,4)
print(b)
c= b.reshape(4,6)
print(c)
print(c.flags)
print(b.itemsize)
print(c.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

4
4


In [38]:
print(np.empty([2,3]))
print(np.ones([2,3]))
print(np.zeros([2,3]))

[[1. 0. 2.]
 [0. 4. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
e = (1,4,5,6,7)
f = np.asarray(e)
g = [(6,7,9,6),8,9]
print(f)
print(g)

[1 4 5 6 7]
[(6, 7, 9, 6), 8, 9]


In [63]:
s = 'Hello World'
f = np.frombuffer(s)
print(f)

TypeError: a bytes-like object is required, not 'str'

In [55]:
list = range(5)
it = iter(list)
x = np.fromiter(it, dtype=complex)
print(x)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [58]:
y = np.linspace(1,24,6)
print(y)
z = np.logspace(1,24,6)
print(z)

[ 1.   5.6 10.2 14.8 19.4 24. ]
[1.00000000e+01 3.98107171e+05 1.58489319e+10 6.30957344e+14
 2.51188643e+19 1.00000000e+24]


In [77]:
x = np.arange(10)
print(x[1:7:])

[1 2 3 4 5 6]


In [67]:
a = [45,95,59,62,32,85,41,20]
b=[0]
b.remove(0)
for i in a :
    if (i >= 60) :
       print(i)
       b.append(i)
print(b)
b.reverse()
print(b)
b.sort()
print(b)
b.reverse()
print(b)

95
62
85
[95, 62, 85]
[85, 62, 95]
[62, 85, 95]
[95, 85, 62]
