In [4]:
import os

In [3]:
container = open("sample.txt" , "r")
print(container.readable())
for item in container.readlines() :
    print(item)
container.close()


True
one,two,three

2,5,9

6,3,4

9,6,5


In [6]:
import numpy as np

arr = np.array([[1, 4, 7], [5,2,9] , [4, 6,8]])
iden = np.array([[2,0,0] , [0,2,0] , [0,0,2]])
arr1 = np.array([2,4,6])



[2.   2.75 3.5  4.25 5.   5.75 6.5  7.25 8.  ]


In [10]:
print(np.dot(arr, arr1))

[60 72 80]


In [11]:
print((arr * arr1))

[[ 2 16 42]
 [10  8 54]
 [ 8 24 48]]


In [13]:
print(arr.shape)

(3, 3)


In [22]:
print(arr.dtype)

int32


In [23]:
print(np.matmul(arr,iden))

[[ 2  8 14]
 [10  4 18]
 [ 8 12 16]]


In [ ]:
res = ma @ iden

In [38]:
np.savetxt('result.txt',fmt='%5.2f',delimiter=',')

TypeError: _savetxt_dispatcher() missing 1 required positional argument: 'X'

In [27]:
print(np.arange(3,34,2).reshape(4,4))

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]]


In [28]:
print(np.linspace(2,8,9))

[2.   2.75 3.5  4.25 5.   5.75 6.5  7.25 8.  ]
