In [1]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [2]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [4]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

5


In [5]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [7]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...] )
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [1]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print  (y)

[1 4 5]


In [2]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:') 
print (x) 
print ('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:') 
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [3]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x) 
print ('\n')  

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:') 
print (z )
print ('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print ('Slicing using advanced index for column:') 
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [4]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print ( x )
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [5]:
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print (a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [13]:
import numpy as np 
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [10]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (*c)

10 40 90 160
